<?php
$spa = true;
$anchorStyle = ($spa) ? $context->getAnchorStyle() : 'classic';
$current = 'community';
?>

<!-- Display header on MPA mode -->
<?php if (!$spa) : ?>
	<?php 
		$this->current = 'admin';
		echo $this->partial('/partials/menu'); 
	?>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
<?php endif;?>

		<div class="panel panel-default">
            <div class="panel-heading">
				<?php echo $this->translate('Community', 'ppit-contact', $context->getLocale()) ?>
            </div>
		    <div class="panel-body">
				<table class="table-condensed">
					<tr>
						<td colspan="2">
<!-- Go to contacts -->
							<?php echo $this->partial('/partials/anchor-widget.phtml', array(
									'text' => $this->translate('Contacts', 'ppit-contact', $context->getLocale()),
									'id' => 'vcard-anchor',
									'anchorStyle' => $anchorStyle,
									'spa' => $spa,
							)) ?>
			    		</td>
			    	</tr>
			    </table>

		    	<div class="row">

<!-- Filter on name -->
				    <div class="col-md-6">
						<div class="form-group has-feedback">
							<label class="control-label" for="community_name"><?php echo $this->translate('Name', 'ppit-core', $context->getLocale()) ?></label>
							<input type="text" class="form-control" id="community_name"/>
							<span class="glyphicon glyphicon-search form-control-feedback"></span>
						</div>
					</div>

				</div>

<!-- Add or update section -->
				<div id="community_list"></div>
				
			</div>
		</div>
<?php if (!$spa) : ?>
	</div>
</div>
<?php endif;?>

<script id="community_index_script">

// Go to contacts
<?php echo $this->partial('/partials/show-main-script', array(
		'id' => 'vcard-anchor',
		'route' => $this->url('vcard/index', array('instance_id' => $context->getInstanceId(), 'community_id' => $context->getCommunityId())),
		'script' =>'vcard_index_script',
		'hideForm' => true,
		'spa' => $spa,
)) ?>

// Add or update section
function getCommunityList(param, input) {
	var xhttp = new XMLHttpRequest();
	xhttp.onreadystatechange = function() {
		if (xhttp.readyState == 4 && xhttp.status == 200) {
			document.getElementById('community_list').innerHTML = xhttp.responseText;
<?php if ($config['ppitCoreSettings']['isTraceActive']) : ?>
			console.log('getCommunityList, route = ' + '<?php echo $this->url('community/list') ?>?' + param + '=' + input);
			console.log(xhttp.responseText);
<?php endif;?>
			eval(document.getElementById('community_list_script').innerHTML);
		}
	}
	xhttp.open('GET', '<?php echo $this->url('community/list') ?>?' + param + '=' + input, true);
	xhttp.send();
}

$('#community_name').keyup(function () {
	var input = document.getElementById('community_name').value;
	if (input == '' || input.length >= 2) {
		getCommunityList('name', input);
	}
	else {
		document.getElementById('community_list').innerHTML = '';
	}
});
$('#community_name').focus();

getCommunityList('name', '');

</script>