<?php 
$spa = true;
$anchorStyle = ($spa) ? $context->getAnchorStyle() : 'classic';
$isDeletable = $community->isDeletable();
?>

<!-- Display header on MPA mode -->
<?php if (!$spa) : ?>
	<?php 
		$this->current = 'community';
		echo $this->partial('/partials/menu'); 
	?>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
<?php endif;?>

		<div class="panel panel-default">
            <div class="panel-heading">
				<?php echo $this->translate('Community: '.(($id) ? 'update' : 'add'), 'ppit-contact', $context->getLocale()) ?>
 				<div class="btn-group pull-right">
					<?php echo $this->partial('/partials/anchor-widget.phtml', array(
							'glyphicon' => 'glyphicon-remove',
							'title' => $this->translate('Return to list', 'ppit-core', $context->getLocale()),
							'id' => 'remove-anchor',
							'anchorStyle' => $anchorStyle,
							'spa' => $spa,
					)) ?>
 				</div>
			</div>
           	<div class="panel-body">
				<table class="table-condensed">
					<tr>
						<td>

<?php if ($id) : ?>
<!-- Delete -->
							<?php echo $this->partial('/partials/anchor-widget.phtml', array(
									'glyphicon' => 'glyphicon-trash',
									'title' => $this->translate('Delete', 'ppit-core', $context->getLocale()),
									'id' => 'delete-anchor',
									'anchorStyle' => $anchorStyle,
									'class' => ($isDeletable) ? 'btn-danger' : 'btn-disabled',
									'disabled' => !$isDeletable,
									'spa' => $spa,
							)) ?>
<?php endif;?>
						</td>
					</tr>

				</table>

<!-- Form header -->
<?php echo $this->partial('/partials/form-header', array(
			'id' => $id,
			'update_time' => $community->update_time,
			'message' => $message,
			'error' => $error,
			'csrfForm' => $csrfForm,
			'context' => $context,
)) ?>

<?php if ($message == 'OK' || !$context->isAllowed('community/update')) $isDisabled = true; else $isDisabled = false; ?>

<!-- Name -->

	<?php
		echo $this->partial('/partials/input-widget.phtml', array(
			'property' => 'name',
			'label' => $this->translate('Name', 'ppit-core', $context->getLocale()),
			'value' => $community->name,
			'isMandatory' => true,
			'maxLength' => 255,
			'context' => $context,
			'isDisabled' => $isDisabled,
	)); ?>
	
<!-- Form footer -->
<?php echo $this->partial('/partials/form-footer') ?>

<!-- Authorization section -->
				<div id="community_function_list"></div>

			</div>
		</div>
<?php if (!$spa) : ?>
	</div>
</div>
<?php endif;?>

<script id='community_update_script'>

// Close form
<?php echo $this->partial('/partials/form-return-script', array(
		'id' => 'remove-anchor',
		'route' => $this->url('community/index'),
		'spa' => $spa,
)) ?>

// Add
<?php echo $this->partial('/partials/show-form-script', array(
		'id' => 'add-anchor',
		'route' => $this->url('community/update'),
		'script' =>'community_update_script',
		'spa' => $spa,
)) ?>

// Delete
<?php echo $this->partial('/partials/show-form-script', array(
		'id' => 'delete-anchor',
		'route' => $this->url('community/delete', array('id' => $id)),
		'script' =>'community_delete_script',
		'spa' => $spa,
)) ?>

<?php if ($message == 'OK') : ?>

<?php echo $this->partial('/partials/form-return-script', array(
		'id' => 'foot-return-anchor',
		'route' => $this->url('community/index'),
		'spa' => $spa,
)) ?>

<?php else : ?>

<?php echo $this->partial('/partials/form-return-script', array(
		'id' => 'cancel-anchor',
		'route' => $this->url('community/index'),
		'spa' => $spa,
)) ?>

// Submit
<?php
$properties = array('name' => 'input', 'update_time' => 'hidden');
echo $this->partial('/partials/form-button-script', array(
		'context' => $context,
		'id' => 'submit-button',
		'formRoute' => $this->url('community/update', array('id' => $id)),
		'formScript' => 'community_update_script',
		'properties' => $properties,
		'mainRoute' => $this->url('community/index'),
		'mainScript' =>'community_index_script',
		'hideForm' => false,
)) ?>

<?php endif;?>

<?php if ($id) : ?>
	
	// Community function section
	function getContractList() {
		var xhttp = new XMLHttpRequest();
		xhttp.onreadystatechange = function() {
			if (xhttp.readyState == 4 && xhttp.status == 200) {
				document.getElementById('community_function_list').innerHTML = xhttp.responseText;
	<?php if ($config['ppitCoreSettings']['isTraceActive']) : ?>
				console.log('getContractList, route = ' + '<?php echo $this->url('contract/list') ?>');
				console.log(xhttp.responseText);
	<?php endif;?>
				eval(document.getElementById('community_function_list_script').innerHTML);
			}
		}
		xhttp.open('GET', '<?php echo $this->url('contract/list', array('community_id' => $community->id)) ?>', true);
		xhttp.send();
	}
	
	getContractList();

<?php endif;?>

</script>
