
<!-- Title -->
				    <div class="form-group" id="<?php echo $prefix ?>n_title_group">
						<label class="col-sm-5 control-label"><?php echo $this->translate('Title', 'ppit-contact', $currentUser->locale) ?></label>
						<div class="col-sm-7">
							<input name="<?php echo $prefix ?>n_title" id="<?php echo $prefix ?>n_title" class="form-control" value="<?php echo $contact->n_title ?>"<?php if ($message == 'OK') echo 'disabled="disabled"' ?>>
						</div>
						<div class="col-sm-12"><p class="help-block" id="<?php echo $prefix ?>n_title_error"></p></div>
					</div>
					
<!-- Last name -->
				    <div class="form-group" id="<?php echo $prefix ?>n_last_group">
						<label class="col-sm-5 control-label">* <?php echo $this->translate('Last name', 'ppit-contact', $currentUser->locale) ?></label>
						<div class="col-sm-7">
							<input name="<?php echo $prefix ?>n_last" id="<?php echo $prefix ?>n_last" list="<?php echo $prefix ?>contacts" class="form-control" value="<?php echo $contact->n_last ?>" autocomplete="off" onselect="<?php echo $prefix ?>autocompletion()"<?php if ($message == 'OK') echo 'disabled="disabled"' ?>>
							<datalist id="<?php echo $prefix ?>contacts">
<?php foreach ($vcards as $vcard) : ?>
							  <option value="<?php echo $vcard->id ?>" label="<?php echo $vcard->n_fn ?> - <?php echo ($contact->email) ? $contact->email : ($contact->tel_cell) ? $vcard->tel_cell : $vcard->tel_work ?>">
<?php endforeach;?>
							</datalist>
						</div>
						<div class="col-sm-12"><p class="help-block" id="<?php echo $prefix ?>n_last_error"></p></div>
					</div>

<!-- First name -->
				    <div class="form-group" id="<?php echo $prefix ?>n_first_group">
						<label class="col-sm-5 control-label">* <?php echo $this->translate('First name', 'ppit-contact', $currentUser->locale) ?></label>
						<div class="col-sm-7">
							<input name="<?php echo $prefix ?>n_first" id="<?php echo $prefix ?>n_first" class="form-control" value="<?php echo $contact->n_first ?>"<?php if ($message == 'OK') echo 'disabled="disabled"' ?>>
						</div>
						<div class="col-sm-12"><p class="help-block" id="<?php echo $prefix ?>n_first_error"></p></div>
					</div>
					
<!-- Email -->
				    <div class="form-group" id="<?php echo $prefix ?>email_group">
						<label class="col-sm-5 control-label">* <?php echo $this->translate('Email', 'ppit-contact', $currentUser->locale) ?></label>
						<div class="col-sm-7">
							<input name="<?php echo $prefix ?>email" id="<?php echo $prefix ?>email" class="form-control" value="<?php echo $contact->email ?>"<?php if ($message == 'OK') echo 'disabled="disabled"' ?>>
						</div>
						<div class="col-sm-12"><p class="help-block" id="<?php echo $prefix ?>email_error"></p></div>
					</div>

<!-- Work phone -->
				    <div class="form-group" id="<?php echo $prefix ?>tel_work_group">
						<label class="col-sm-5 control-label">* <?php echo $this->translate('Work phone', 'ppit-contact', $currentUser->locale) ?></label>
						<div class="col-sm-7">
							<input name="<?php echo $prefix ?>tel_work" id="<?php echo $prefix ?>tel_work" class="form-control" value="<?php echo $contact->tel_work ?>"<?php if ($message == 'OK') echo 'disabled="disabled"' ?>>
						</div>
						<div class="col-sm-12"><p class="help-block" id="<?php echo $prefix ?>tel_work_error"></p></div>
					</div>

<!-- Cellular phone -->
				    <div class="form-group" id="<?php echo $prefix ?>tel_cell_group">
						<label class="col-sm-5 control-label"> <?php echo $this->translate('Cellular phone', 'ppit-contact', $currentUser->locale) ?></label>
						<div class="col-sm-7">
							<input name="<?php echo $prefix ?>tel_cell" id="<?php echo $prefix ?>tel_cell" class="form-control" value="<?php echo $contact->tel_cell ?>"<?php if ($message == 'OK') echo 'disabled="disabled"' ?>>
						</div>
						<div class="col-sm-12"><p class="help-block" id="<?php echo $prefix ?>tel_cell_error"></p></div>
					</div>

<!-- Properties -->
<?php foreach ($properties as $property_name => $property) : ?>
					<div class="form-group" id="<?php echo $prefix ?><?php echo $property_name ?>_group">
						<label class="col-sm-5 control-label"> <?php echo $this->translate($property->caption, 'ppit-contact', $currentUser->locale) ?></label>
						<div class="col-sm-7">
							<input name="<?php echo $prefix ?><?php echo $property_name ?>" id="<?php echo $prefix ?><?php echo $property_name ?>" class="form-control" value="<?php echo $property->text_value ?>"<?php if ($message == 'OK') echo 'disabled="disabled"' ?>>
						</div>
						<div class="col-sm-12"><p class="help-block" id="<?php echo $prefix ?><?php echo $property_name ?>_error"></p></div>
					</div>
<?php endforeach;?>

<script>

//contactCheckEmail returns null if the given email is valid, else a localized error message
function contactCheckEmail(value) {

	// Regex for email format
	var emailFormat = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/;
	
	if(!emailFormat.test(value)) {
		return "<?php echo $this->translate('Invalid email format', 'ppit-contact', $currentUser->locale); ?>";
	}
 return null;
}

//contactCheckPhone returns null if the given phone number is valid, else a localized error message
function contactCheckPhone(value) {

	// Regex for phone format
	var phoneFormat = /^\+?([0-9\. ]*)$/;
	
	if(!phoneFormat.test(value)) {
		return "<?php echo $this->translate('Invalid phone format', 'ppit-contact', $currentUser->locale); ?>";
	}
return null;
}

function contactRenderElement(elementId, error) {

	if (error) {
		document.getElementById(elementId + "_group").className = "form-group has-error";
		document.getElementById(elementId + "_error").innerHTML = error;
		document.getElementById(elementId + "_error").style.display = "block";
		document.getElementById(elementId).focus();
	}
	else {
		document.getElementById(elementId + "_group").className = "form-group";
		document.getElementById(elementId + "_error").innerHTML = "";
 	document.getElementById(elementId + "_error").style.display = "none";
	}
}

function <?php echo $prefix ?>autocompletion() {
	var id = document.getElementById("<?php echo $prefix ?>n_last").value;
	
	var xhttp = new XMLHttpRequest(), obj;
	xhttp.onreadystatechange = function() {
		if (xhttp.readyState == 4 && xhttp.status == 200) {
			var id = document.getElementById("<?php echo $prefix ?>n_last").value;
			obj = JSON.parse(xhttp.responseText).data;
			document.getElementById("<?php echo $prefix ?>n_title").value = obj.n_title;
			document.getElementById("<?php echo $prefix ?>n_first").value = obj.n_first;
			document.getElementById("<?php echo $prefix ?>n_last").value = obj.n_last;
			document.getElementById("<?php echo $prefix ?>email").value = obj.email;
			document.getElementById("<?php echo $prefix ?>tel_work").value = obj.tel_work;
			document.getElementById("<?php echo $prefix ?>tel_cell").value = obj.tel_cell;
<?php foreach ($properties as $property_name => $property) : ?>
			document.getElementById("<?php echo $prefix ?><?php echo $property_name ?>").value = obj.<?php echo $property_name ?>;
<?php endforeach; ?>
		}
	}
	xhttp.open("GET", "<?php echo $this->url('vcardRest') ?>/" + id, true);
	xhttp.send();
}

function <?php echo $prefix ?>disable()
{
	document.getElementById("<?php echo $prefix ?>n_title").disabled = "disabled";
	document.getElementById("<?php echo $prefix ?>n_first").disabled = "disabled";
	document.getElementById("<?php echo $prefix ?>n_last").disabled = "disabled";
	document.getElementById("<?php echo $prefix ?>email").disabled = "disabled";
	document.getElementById("<?php echo $prefix ?>tel_work").disabled = "disabled";
	document.getElementById("<?php echo $prefix ?>tel_cell").disabled = "disabled";
}	

// The elements are checked last to first so the focus is positionned on the first element on error
function <?php echo $prefix ?>checkContact() 
{
//	var validity = true, error;
	
// Properties
<?php foreach ($properties as $property => $property_caption) : ?>
	if (document.getElementById("<?php echo $prefix ?><?php echo $property ?>").value.length > 255) {
		contactRenderElement("<?php echo $prefix ?><?php echo $property ?>", "<?php echo $this->translate('The input is too long', 'ppit-core', $currentUser->locale) ?>");
		validity = false;
	}
    else {
		contactRenderElement("<?php echo $prefix ?><?php echo $property ?>", null);
	}
<?php endforeach;?>

	// Cellular phone
	var tel_cell_validity = true;
	error = contactCheckPhone(document.getElementById('<?php echo $prefix ?>tel_cell').value);
	if (error) {
		contactRenderElement("<?php echo $prefix ?>tel_cell", error);
		validity = tel_cell_validity = false;
	}
	    else {
		contactRenderElement("<?php echo $prefix ?>tel_cell", null);
	}
	
	// Work phone
	var tel_work_validity = true;
	error = contactCheckPhone(document.getElementById('<?php echo $prefix ?>tel_work').value);
	if (error) {
		contactRenderElement("<?php echo $prefix ?>tel_work", error);
		validity = tel_work_validity = false;
	}
	else {
		contactRenderElement("<?php echo $prefix ?>tel_work", null);
	}

	// 1 mandatory phone
	if (tel_cell_validity && tel_work_validity) {
		if (document.getElementById("<?php echo $prefix ?>tel_work").value == "" && document.getElementById("<?php echo $prefix ?>tel_cell").value == "") {
			contactRenderElement("<?php echo $prefix ?>tel_cell", "<?php echo $this->translate('Please input at least one phone', 'ppit-contact', $currentUser->locale) ?>");
			contactRenderElement("<?php echo $prefix ?>tel_work", "<?php echo $this->translate('Please input at least one phone', 'ppit-contact', $currentUser->locale) ?>");
			validity = false;
		}
	    else {
			contactRenderElement("<?php echo $prefix ?>tel_cell", null);
	    	contactRenderElement("<?php echo $prefix ?>tel_work", null);
		}
	}
	
	// Email
	var email_validity = true;
	var email = document.getElementById('<?php echo $prefix ?>email').value;
	if (email == "") contactRenderElement("<?php echo $prefix ?>email", null);
	else {
		error = contactCheckEmail(email);
		if (error) {
			contactRenderElement("<?php echo $prefix ?>email", error);
			validity = email_validity = false;
		}
	    else {
			contactRenderElement("<?php echo $prefix ?>email", null);
		}
	}
	
	// At least email or cellular
	if (tel_cell_validity && email_validity) {
		if (document.getElementById("<?php echo $prefix ?>tel_cell").value == "" && document.getElementById("<?php echo $prefix ?>email").value == "") {
			contactRenderElement("<?php echo $prefix ?>email", "<?php echo $this->translate('Please input at least the cellular or the email', 'ppit-contact', $currentUser->locale) ?>");
			contactRenderElement("<?php echo $prefix ?>tel_cell", "<?php echo $this->translate('Please input at least the cellular or the email', 'ppit-contact', $currentUser->locale) ?>");
			validity = false;
		}
	    else {
			contactRenderElement("<?php echo $prefix ?>email", null);
	    	contactRenderElement("<?php echo $prefix ?>tel_cell", null);
		}
	}
	
	// First name
	if (document.getElementById("<?php echo $prefix ?>n_first").value == "") {
		contactRenderElement("<?php echo $prefix ?>n_first", "<?php echo $this->translate('Please input the first name', 'ppit-contact', $currentUser->locale) ?>");
		validity = false;
	}
    else if (document.getElementById("<?php echo $prefix ?>n_first").value.length > 255) {
		contactRenderElement("<?php echo $prefix ?>n_last", "<?php echo $this->translate('The input is too long', 'ppit-core', $currentUser->locale) ?>");
		validity = false;
	}
    else {
		contactRenderElement("<?php echo $prefix ?>n_first", null);
	}
	
	// Last name
	if (document.getElementById("<?php echo $prefix ?>n_last").value == "") {
		contactRenderElement("<?php echo $prefix ?>n_last", "<?php echo $this->translate('Please input the last name', 'ppit-contact', $currentUser->locale) ?>");
		validity = false;
	}
    else if (document.getElementById("<?php echo $prefix ?>n_last").value.length > 255) {
		contactRenderElement("<?php echo $prefix ?>n_last", "<?php echo $this->translate('The input is too long', 'ppit-core', $currentUser->locale) ?>");
		validity = false;
	}
    else {
		contactRenderElement("<?php echo $prefix ?>n_last", null);
	}
	
	// Title
	if (document.getElementById("<?php echo $prefix ?>n_title").value.length > 255) {
		contactRenderElement("<?php echo $prefix ?>n_title", "<?php echo $this->translate('The input is too long', 'ppit-core', $currentUser->locale) ?>");
		validity = false;
	}
    else {
		contactRenderElement("<?php echo $prefix ?>n_title", null);
	}
	
	return validity;
}

</script>
