<!-- 
/**
 * PpitCore V1.0 (https://github.com/p-pit/PpitCore)
 *
 * @link      https://github.com/p-pit/PpitCore
 * @copyright Copyright (c) 2016 Bruno Lartillot
 * @license   https://github.com/p-pit/PpitCore/blob/master/license.txt GNU-GPL license
 */
-->

<div class="panel panel-default">
	<div class="panel-heading" style="background:  <?php echo $context->getConfig('styleSheet')['panelHeadingBackground'] ?>; color: <?php echo $context->getConfig('styleSheet')['panelHeadingColor'] ?>">
		<strong><?php echo ($contactMessage->id) ? $this->translate('Detail', 'ppit-core', $context->getLocale()) : $this->translate('Add', 'ppit-core', $context->getLocale()) ?></strong>
 		<div class="btn-group pull-right">
			<button type="button" class="btn btn-default" title="<?php echo $this->translate('Return to list', 'ppit-core', $context->getLocale()) ?>" id="remove-anchor">
				<span class="glyphicon glyphicon-remove"></span>
			</button>
 		 </div>
	</div>
	<div class="panel-body">

		<div class="tab-content">
			<div class="tab-pane fade in active" id="contact-message-update-panel"></div>
		</div>
	</div>
	