<!-- 
/**
 * PpitCore V1.0 (https://github.com/p-pit/PpitCore)
 *
 * @link      https://github.com/p-pit/PpitCore
 * @copyright Copyright (c) 2016 Bruno Lartillot
 * @license   https://github.com/p-pit/PpitCore/blob/master/license.txt GNU-GPL license
 */
-->

<table class="table table-striped ppit_index">
	<tr>
		<th>&nbsp;</th>

<?php foreach ($context->getConfig('contactMessage/list') as $propertyId => $rendering) : ?>
	<?php 
	$property = $context->getConfig('contactMessage')['properties'][$propertyId];
	if ($property['type'] == 'repository') $property = $context->getConfig($property['definition']);
	?>
		<th align="center">
	<?php $label = $property['labels'][$context->getLocale()] ?>
	<?php if ($label) : ?>
			<button type="button" class="btn btn-default btn-xs ppit-sort-anchor" id="<?php echo $propertyId ?>-anchor">
				<span><?php echo $label ?></span>
<?php if ($major == $propertyId) : ?>
				<span class="glyphicon glyphicon-triangle-<?php echo ($dir == 'ASC') ? 'top' : 'bottom' ?>"></span>
<?php endif ?>
			</button>
	<?php endif;?>
		</th>
<?php endforeach;?>

		<th>&nbsp;</th>
	</tr>
	
	<tr class="place">
		<td style="text-align: center">
			<button type="button" class="btn btn-default index-btn contact-message-detail-anchor" title="<?php echo $this->translate('Detail', 'ppit-core', $context->getLocale())?>" id="contact-message-detail-anchor_0">
				<span class="glyphicon glyphicon-plus" id="add-glyphicon"></span>
			</button>
		</td>
		<td colspan="7">&nbsp;</td>
	</tr>

<?php foreach ($contactMessages as $contactMessage) : ?>
	
	<tr class="contact-message">
	
		<td style="text-align: center">
			<button type="button" class="btn btn-default index-btn contact-message-detail-anchor" title="<?php echo $this->translate('Detail', 'ppit-core', $context->getLocale())?>" id="contact-message-detail-anchor_<?php echo $contactMessage->id ?>">
				<span class="glyphicon glyphicon-zoom-in" id="<?php echo $contactMessage->id ?>-glyphicon"></span>
			</button>
		</td>

	<?php foreach ($context->getConfig('contactMessage/list') as $propertyId => $rendering) : ?>
	
		<?php if ($rendering == 'date') : ?>
		<td><?php echo $context->decodeDate($contactMessage->properties[$propertyId]) ?></td>

		<?php elseif ($rendering == 'number') : ?>
		<td style="text-align: right"><?php echo $context->formatFloat($contactMessage->properties[$propertyId], 2) ?></td>

		<?php elseif ($rendering =='select') : ?>
			<?php 
			$property = $context->getConfig('contactMessage')['properties'][$propertyId];
			if ($property['type'] == 'repository') $property = $context->getConfig($property['definition']);
			?>
		<td><?php echo $property['modalities'][$contactMessage->properties[$propertyId]][$context->getLocale()] ?></td>

		<?php elseif ($rendering =='array') : ?>
		<td><?php echo implode(' ', $contactMessage->properties[$propertyId]) ?></td>

		<?php else : ?>
		<td><?php echo $contactMessage->properties[$propertyId] ?></td>

		<?php endif;?>
		
	<?php endforeach;?>
	</tr>
	
<?php endforeach; ?>

</table>
