<?php
$spa = $context->isSpaMode();
$anchorStyle = ($spa) ? $context->getAnchorStyle() : 'classic';
?>

<!-- Display header on MPA mode -->
<?php if (!$spa) : ?>
	<?php 
		echo $this->partial('/partials/menu'); 
	?>
<?php endif;?>

<h4><?php echo $this->translate('Delete a function', 'ppit-contact', $context->getLocale()) ?></h4>

<table class="table-condensed">
	<tr>
		<td class="ppit-header-caption"><?php echo $this->translate('Customer', 'ppit-contact', $context->getLocale())?></td>
		<td><?php echo $contract->customer_name ?>
	</tr>
	<tr>
		<td class="ppit-header-caption"><?php echo $this->translate('Supplyer', 'ppit-contact', $context->getLocale())?></td>
		<td><?php echo $contract->supplyer_name ?>
	</tr>
	<tr>
		<td class="ppit-header-caption"><?php echo $this->translate('Function', 'ppit-core', $context->getLocale())?></td>
		<td><?php echo $this->translate($config['ppitContactSettings']['functions'][$contract->function], 'ppit-core', $context->getLocale()) ?>
	</tr>
	<tr>
		<td class="ppit-header-caption"><?php echo $this->translate('Opening date', 'ppit-core', $context->getLocale())?></td>
		<td><?php echo $context->decodeDate($contract->opening_date) ?>
	</tr>
	<tr>
		<td class="ppit-header-caption"><?php echo $this->translate('Closing date', 'ppit-core', $context->getLocale())?></td>
		<td><?php echo $context->decodeDate($contract->closing_date) ?>
	</tr>
</table>

<!-- Form header -->
<?php echo $this->partial('/partials/form-header', array(
	'formId' => 'community-function-delete-form',
	'update_time' => $contract->update_time,
	'message' => $message,
	'error' => $error,
	'csrfForm' => $csrfForm,
	'context' => $context,
)) ?>

<!-- Form footer -->
<?php echo $this->partial('/partials/form-footer', array(
	'prefix' => 'community_function_',
	'class' => 'btn-danger',
	'message' => $message,
	'context' => $context,
)) ?>

			</div>
		</div>

<script id='community_function_delete_script'>

<?php if ($message == 'OK') : ?>

	$('#community_function_foot-return-anchor').click(function () {
		reload(
			'<?php echo $this->url('contract/list') ?>',
			'community_function_list_script',
			'community_function_list'
		);
	} );

<?php else : ?>

	$('#community_function_cancel-anchor').click(function () {
		reload(
			'<?php echo $this->url('contract/list') ?>',
			'community_function_list_script',
			'community_function_list'
		);
	} );

// Submit
	<?php echo $this->partial('/partials/form-button-script', array(
			'context' => $context,
			'formId' => 'community-function-delete-form',
			'id' => 'submit-button',
			'formRoute' => $this->url('contract/delete', array('id' => $id)),
			'formScript' =>'community_function_delete_script',
			'target' => 'community_function_list',
			'properties' => array('update_time' => 'hidden'),
			'mainRoute' => null,
			'hideForm' => false,
	)) ?>

<?php endif;?>

</script>
