<?php
$spa = true;
$anchorStyle = ($spa) ? $context->getAnchorStyle() : 'classic';
?>

<h4><?php echo $this->translate('Accessible functions per supplyer', 'ppit-contact', $context->getLocale()) ?></h4>

				<table class="table table-striped ppit_index">
					<tr>
						<th>&nbsp;</th>
						<th><strong>
							<?php echo $this->partial('/partials/anchor-widget.phtml', array(
									'text' => $this->translate('Customer', 'ppit-contact', $context->getLocale()),
									'id' => 'customer-name-anchor',
									'anchorStyle' => $context->getAnchorStyle(),
									'spa' => $spa,
							)) ?>
						</strong></th>
						<th><strong>
							<?php echo $this->partial('/partials/anchor-widget.phtml', array(
									'text' => $this->translate('Supplyer', 'ppit-contact', $context->getLocale()),
									'id' => 'supplyer-caption-anchor',
									'anchorStyle' => $context->getAnchorStyle(),
									'spa' => $spa,
							)) ?>
						</strong></th>
						<th><strong>
							<?php echo $this->partial('/partials/anchor-widget.phtml', array(
									'text' => $this->translate('Function', 'ppit-core', $context->getLocale()),
									'id' => 'function-anchor',
									'anchorStyle' => $context->getAnchorStyle(),
									'spa' => $spa,
							)) ?>
						</strong></th>
					</tr>

					<tr>
						<td colspan="4">
<!-- Add -->
							<?php echo $this->partial('/partials/anchor-widget.phtml', array(
									'glyphicon' => 'glyphicon-plus',
									'title' => $this->translate('Add', 'ppit-core', $context->getLocale()),
									'id' => 'community-function-add-anchor',
									'anchorStyle' => $anchorStyle,
									'spa' => $spa,
									'showForm' => true,
							)) ?>
						</td>
					</tr>

<?php foreach ($contracts as $contract) : ?>
					<tr>

<!-- delete -->
						<td>
							<?php echo $this->partial('/partials/anchor-widget.phtml', array(
									'glyphicon' => 'glyphicon-trash',
									'title' => $this->translate('Detail', 'ppit-core', $context->getLocale()),
									'id' => 'community-function-delete-anchor-'.$contract->id,
									'anchorStyle' => $context->getAnchorStyle(),
									'spa' => $spa,
									'showForm' => true,
							)) ?>
						</td>

						<td><?php echo $contract->customer_name ?></td>
						<td><?php echo $contract->supplyer_name ?></td>
						<td><?php echo $this->translate($config['ppitContactSettings']['functions'][$contract->function], 'ppit-core', $context->getLocale()) ?></td>

					</tr>
<?php endforeach; ?>
				</table>
		
<script id='community_function_list_script'>

// Sort on customer
$('#customer-name-anchor').click(function () {
	reload(
		'<?php echo $this->url('contract/list').'?major=customer_name'.(($major == 'customer_name' && $dir =='ASC') ? '&dir=DESC' : '&dir=ASC') ?>',
		'community_function_list_script',
		'community_function_list'
	);
} );

// Sort on supplyer
$('#supplyer-caption-anchor').click(function () {
	reload(
		'<?php echo $this->url('contract/list').'?major=supplyer_name'.(($major == 'supplyer_name' && $dir =='ASC') ? '&dir=DESC' : '&dir=ASC') ?>',
		'community_function_list_script',
		'community_function_list'
	);
} );

// Sort on function
$('#function-anchor').click(function () {
	reload(
		'<?php echo $this->url('contract/list').'?major=function'.(($major == 'function' && $dir =='ASC') ? '&dir=DESC' : '&dir=ASC') ?>',
		'community_function_list_script',
		'community_function_list'
	);
} );

// Add
$('#community-function-add-anchor').click(function () {
	reload(
		'<?php echo $this->url('contract/add') ?>',
		'community_function_add_script',
		'community_function_list'
	);
} );

<?php foreach ($contracts as $contract) : ?>
	
	// Delete
	$('#community-function-delete-anchor-<?php echo $contract->id ?>').click(function () {
		reload(
			'<?php echo $this->url('contract/delete', array('id' => $contract->id)) ?>',
			'community_function_delete_script',
			'community_function_list'
		);
	} );

<?php endforeach;?>

</script>
