<style>
.ppit-th {
	font-weight: bold;
	background-color: #eFeFeF;
}
</style>

<?php 
$spa = $context->isSpaMode();
$anchorStyle = ($spa) ? $context->getAnchorStyle() : 'classic';
?>

<!-- Display header on MPA mode -->
<?php if (!$spa) : ?>
	<?php 
		$this->current = 'vcard';
		echo $this->partial('/partials/menu'); 
	?>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
<?php endif;?>

		<div class="panel panel-default">
            <div class="panel-heading"><strong><?php echo $this->translate('Messages', 'ppit-contact', $context->getLocale()) ?></strong></div>
           	<div class="panel-body">
				<table class="table-condensed">
				    <tr>
						<td>
							<strong><a href="<?php echo $this->url('vcard')?>"><?php echo $this->translate('Contacts', 'ppit-contact', $context->getLocale()) ?></a></strong>
						</td>
					</tr>
				</table>
	           	<table class="table table-striped">
					<tr>
						<th class="ppit-th">&nbsp;</th>
						<th class="ppit-th">
							<a href="<?php echo $this->url($this->route, array('action' => 'index')) ?>
															?major=type
															<?php if ($major == 'type' && $dir =='ASC') echo '&dir=DESC'; else echo '&dir=ASC' ?>">
								<?php echo $this->translate('Media', 'ppit-contact', $context->getLocale());?>
							</a>
						</th>
						<th class="ppit-th">
							<a href="<?php echo $this->url($this->route, array('action' => 'index')) ?>
															?major=from
															<?php if ($major == 'from' && $dir =='ASC') echo '&dir=DESC'; else echo '&dir=ASC' ?>">
								<?php echo $this->translate('From', 'ppit-contact', $context->getLocale());?>
							</a>
						</th>
						<th class="ppit-th">
							<a href="<?php echo $this->url($this->route, array('action' => 'index')) ?>
															?major=emission_time
															<?php if ($major == 'emission_time' && $dir =='ASC') echo '&dir=DESC'; else echo '&dir=ASC' ?>">
								<?php echo $this->translate('Emission', 'ppit-contact', $context->getLocale());?>
							</a>
						</th>
						<th class="ppit-th">
							<a href="<?php echo $this->url($this->route, array('action' => 'index')) ?>
															?major=cost
															<?php if ($major == 'cost' && $dir =='ASC') echo '&dir=DESC'; else echo '&dir=ASC' ?>">
								<?php echo $this->translate('Cost', 'ppit-contact', $context->getLocale()) ?> (€)
							</a>
						</th>
					</tr>

<!-- Add action -->
					<tr>
						<td colspan="9">
							<?php echo $this->partial('/partials/anchor-widget.phtml', array(
									'glyphicon' => 'glyphicon-plus',
									'title' => $this->translate('Send a message', 'ppit-contact', $context->getLocale()),
									'id' => 'add-anchor',
									'anchorStyle' => $context->getAnchorStyle(),
									'spa' => $spa,
							)) ?>
						</td>
					</tr>

<?php foreach ($messages as $message) : ?>
					<tr>
	
<!-- Update action -->
						<td>
							<?php echo $this->partial('/partials/anchor-widget.phtml', array(
									'glyphicon' => 'glyphicon-zoom-in',
									'title' => $this->translate('Detail', 'ppit-core', $context->getLocale()),
									'id' => 'zoom-anchor-'.$message->id,
									'anchorStyle' => $context->getAnchorStyle(),
									'spa' => $spa,
							)) ?>
						</td>

<!-- Media-->
						<td><?php echo $message->type ?></td>

<!-- From -->
						<td><?php echo $message->from ?></td>

<!-- Emission time-->
<?php if ($message->emission_time) : ?>
<?php 
	$emissionTime = strtotime($message->emission_time);
	$emissionTime = date("d/m/y g:i A", $emissionTime);
?>
						<td><?php echo $emissionTime ?></td>
<?php else : ?>
						<td>&nbsp;</td>
<?php endif;?>

<!-- Cost -->
						<td align="right"><?php echo $context->formatFloat($message->volume * $message->cost, 2) ?></td>
					</tr>

<!-- Subject -->
					<tr>
						<td colspan="9">
							<?php echo $this->translate('Target', 'ppit-contact', $context->getLocale()) ?>: 
							<?php echo (isset($message->to->filter) && $message->to->filter == 'customer') ? $this->translate('Customers', 'ppit-customer', $context->getLocale()) : $this->translate('Any contact', 'ppit-contact', $context->getLocale()) ?> 
							(<?php echo $message->volume ?>)
							<br>
							<?php echo $message->subject ?>
						</td>
					</tr>
<?php endforeach; ?>
				</table>
			</div>
		</div>

<?php if (!$spa) : ?>
	</div>
</div>
<?php endif;?>

<script id="message_script">
</script>