<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="<?php echo $this->basePath('dist/css/main.css') ?>">
  <script src="<?php echo $this->basePath('dist/lib/jquery-3.2.1.min.js') ?>" charset="utf-8"></script>
  <title>Inscription au admission</title>
  <link rel="shortcut icon" href="<?php echo $this->basePath('favicon.ico') ?>" type="image/x-icon">
  <link rel="icon" href="<?php echo $this->basePath('favicon.ico') ?>" type="image/x-icon">
</head>
<body>
  <header class="header">
    <div class="header_container">
      <img src="<?php echo $this->basePath('dist/img/logo.png') ?>" alt="ESI Environment Social Impact Business School" class="header_logo">
      <div class="header_state">
        <div class="header_number header_number-full">1</div>
        <div class="header_line"></div>
        <div class="header_number header_number-full">2</div>
        <div class="header_line"></div>
        <div class="header_number">3</div>
        <div class="header_line"></div>
        <div class="header_number">4</div>
      </div>
    </div>
  </header>
  <section class="state state2">
    <form action="state3.html">
      <h1 class="state_title">Etapes 2 : Formations</h1>
      <div class="state_container">

        <!-- Diplome -->
        <div class="state_module">
          <div class="state_moduleTitleContainer">
            <h2 class="state_moduleTitle">Diplôme obtenu</h2>
          </div>
          <div class="state_moduleContainer state_moduleContainer-large">

            <div class="input_repeater">
              <div class="input_container input_container-grid4">
                <label class="input_label" for="dyear">Année scolaire :</label>
                <input class="input_text" type="text" name="dyear" id="dyear" data-test="number require">
              </div>
              <div class="input_container input_container-grid4">
                <label class="input_label" for="dschool">Etablissement :</label>
                <input class="input_text" type="text" name="dschool" id="dschool" data-test="string require">
              </div>
              <div class="input_container input_container-grid4">
                <label class="input_label" for="dclasse">Classe :</label>
                <input class="input_text" type="text" name="dclasse" id="dclasse">
              </div>
              <div class="input_container input_container-grid4">
                <label class="input_label" for="ddiplome">Diplôme obtenu :</label>
                <input class="input_text" type="text" name="ddiplome" id="ddiplome" data-test="string require">
              </div>
            </div>

            <div class="input_more">
              <div class="input_moreButton">+ Ajouter un autre diplôme</div>
            </div>
          </div>
        </div>

        <!-- Langue -->
        <div class="state_module">
          <div class="state_moduleTitleContainer">
            <h2 class="state_moduleTitle">Langues pratiquées</h2>
          </div>
          <div class="state_moduleContainer">

            <div class="input_repeater">
              <div class="input_container">
                <label class="input_label" for="language">Langue :</label>
                <select class="input_select" name="language" id="language">
                  <option value="japon">Japonais</option>
                  <option value="espagne">Espagnol</option>
                </select>
              </div>

              <div class="input_container">
                <label class="input_label" for="language_level">Nombre d'année d'études :</label>
                <select class="input_select" name="language_level" id="language_level">
                  <option value="1">1 ans</option>
                  <option value="2">2 ans</option>
                  <option value="3">3 ans</option>
                  <option value="4">4 ans</option>
                  <option value="5">5 ans</option>
                  <option value="6">6 ans</option>
                  <option value="7">7 ans</option>
                  <option value="8">8 ans</option>
                  <option value="9">9 ans</option>
                  <option value="10">10 ans</option>
                  <option value="15">Environ 15 ans</option>
                  <option value="20">Environ 20 ans</option>
                  <option value="25">Plus de 25 ans</option>
                </select>
              </div>
            </div>

            <div class="input_more">
              <div class="input_moreButton">+ Ajouter une autre langue</div>
            </div>
          </div>
        </div>

        <!-- Etranger -->
        <div class="state_module">
          <div class="state_moduleTitleContainer">
            <h2 class="state_moduleTitle">Séjour à l'étranger</h2>
          </div>
          <div class="state_moduleContainer">

            <div class="input_repeater">
              <div class="input_container">
                <label class="input_label" for="travels">Pays dans lesquels vous avez séjourné :</label>
                <select class="input_select" name="travels" id="travels">
                  <option value="japon">Japon</option>
                  <option value="espagne">Espagne</option>
                </select>
              </div>

              <div class="input_container">
                <label class="input_label" for="travels_object">Objet des séjours :</label>
                <select class="input_select" name="travels_object" id="travels_object">
                  <option value="study">Etudes</option>
                  <option value="tourist">Tourisme</option>
                  <option value="other">Autre</option>
                </select>
              </div>
            </div>

            <div class="input_more">
              <div class="input_moreButton">+ Ajouter une autre langue</div>
            </div>

          </div>
        </div>

        <div class="state_buttonContainer">
          <button class="state_button" type="submit">
            Étape suivante
            <span class="state_buttonArrow"></span>
          </button>
        </div>
      </div>
    </form>
  </section>
  <script src="<?php echo $this->basePath('dist/js/main.js') ?>" charset="utf-8"></script>
</body>
</html>
