<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="<?php echo $this->basePath('dist/css/main.css') ?>">
  <script src="<?php echo $this->basePath('dist/lib/jquery-3.2.1.min.js') ?>" charset="utf-8"></script>
  <title>Inscription au admission</title>
  <link rel="shortcut icon" href="<?php echo $this->basePath('favicon.ico') ?>" type="image/x-icon">
  <link rel="icon" href="<?php echo $this->basePath('favicon.ico') ?>" type="image/x-icon">
</head>
<body>
  <header class="header">
    <div class="header_container">
      <img src="<?php echo $this->basePath('dist/img/logo.png') ?>" alt="ESI Environment Social Impact Business School" class="header_logo">
      <div class="header_state">
<?php $first = true; foreach ($context->getConfig('contactForm/states') as $stateId => $state) : ?>
	<?php if (!$first) : ?>
        <div class="header_line"></div>
    <?php endif;?>
        <div class="header_number <?php if ($first) echo 'header_number-full' ?>"><?php echo $state['header_number'] ?></div>
<?php $first = false; endforeach;?>
      </div>
    </div>
  </header>
  <section class="state">
    <form action="<?php echo $this->url('contactForm/state', array('state_id' => $state_id, 'id' => $id)) ?>" method="post">
      <h1 class="state_title"><?php echo $currentState['title'][$context->getLocale()]?></h1>

<!-- Duplicate error -->
<?php if ($error == 'Duplicate') : ?>
				<div class="alert alert-danger" style="text-align: center">
					<strong><?php echo $this->translate('This record already exist', 'ppit-core', $context->getLocale()) ?></strong>
				</div>
<?php endif;?>

<!-- Isolation error -->
					<input type="hidden" id="update_time" name="update_time" value="<?php echo (isset($update_time)) ? $update_time : 0 ?>" />
<?php if ($error == 'Isolation') : ?>
				<div class="alert alert-danger" style="text-align: center">
					<strong><?php echo $this->translate('The database has evolved in the meantime, please input again', 'ppit-core', $context->getLocale()) ?></strong>
				</div>
<?php endif;?>

<!-- Consistency error -->
					<input type="hidden" id="update_time" name="update_time" value="<?php echo (isset($update_time)) ? $update_time : 0 ?>" />
<?php if ($error == 'Consistency') : ?>
				<div class="alert alert-danger" style="text-align: center">
					<strong><?php echo $this->translate('The data are not consistent', 'ppit-core', $context->getLocale()) ?></strong>
				</div>
<?php endif;?>

<!--  CSRF -->
<?php $element = $csrfForm->get('csrf') ?>
				    <div class="form-group">
						<?php echo $this->formElement($element) ?>
<?php if ($this->formElementErrors($element)) : ?>
						<div class="alert alert-danger" style="text-align: center">
							<strong><?php echo $this->translate('The form has expired, please input again', 'ppit-core', $context->getLocale()) ?></strong>
						</div>
<?php endif;?>
					</div>

      <div class="state_container">

<?php foreach ($currentState['sections'] as $sectionId => $section) : ?>
        <div class="state_module">
          <div class="state_moduleTitleContainer">
            <h2 class="state_moduleTitle"><?php echo $section['title'][$context->getLocale()]?></h2>
          </div>
          <div class="state_moduleContainer <?php if (array_key_exists('large', $section)) echo 'state_moduleContainer-large' ?>">

	<?php foreach ($section['fields'] as $fieldId => $field) : ?>
		<?php 
		if ($field['type'] == 'repository') $field = $context->getConfig($field['definition']);
		$mandatory = (array_key_exists('mandatory', $field) && $field['mandatory']) ? 'require' : '';
		?>

		<?php if ($field['type'] == 'structured') : ?>
<!-- Structured field -->
			<?php foreach ($field['properties'] as $itemId => $item) : ?>

				<?php if ($item['type'] == 'repeater') : ?>
            <div class="input_repeater">
					<?php foreach ($item['properties'] as $propertyId => $property) : ?>

              <div class="input_container input_container-grid<?php echo count($item['properties']) ?>">
              <label class="input_label" for="<?php echo $propertyId ?>"><?php if ($mandatory) echo '* '?><?php echo $property['labels'][$context->getLocale()]?></label>

						<?php if ($property['type'] == 'select') : ?>
              <select class="input_select" name="<?php echo $propertyId ?>" id="<?php echo $propertyId ?>">
				<option/>
							<?php foreach ($property['modalities'] as $modalityId => $modality) : ?>
                <option value="<?php echo $modalityId?>"><?php echo $modality[$context->getLocale()]?></option>
							<?php endforeach;?>
              </select>

						<?php elseif ($property['type'] == 'textarea') : ?>
              <textarea class="input_textarea" name="<?php echo $propertyId ?>" rows="8" cols="80" data-test="<?php echo $mandatory ?>"></textarea>

						<?php else : ?>
							<?php
							if ($property['type'] == 'text') $type = '';
							elseif ($property['type'] == 'number') $type = 'number';
							elseif ($property['type'] == 'email') $type = 'email';
							elseif ($property['type'] == 'phone') $type = 'number';
							?>
              <input class="input_text" type="text" name="<?php echo $propertyId ?>" id="<?php echo $propertyId ?>" data-test="<?php echo $type ?> <?php echo $mandatory ?>">

						<?php endif?>
              </div>

					<?php endforeach;?>
            </div>

            <div class="input_more">
              <div class="input_moreButton"><?php echo $item['add-button-label'][$context->getLocale()]?></div>
            </div>
        
            	<?php else : ?>
            	<?php 
            	$propertyId = $itemId;
            	$property = $item;
            	?>
            <div class="input_container <?php if (array_key_exists('solo', $property)) echo 'input_container-solo' ?>">
              <label class="input_label" for="<?php echo $propertyId ?>"><?php if ($mandatory) echo '* '?><?php echo $property['labels'][$context->getLocale()]?></label>

					<?php if ($property['type'] == 'select') : ?>
              <select class="input_select" name="<?php echo $propertyId ?>" id="<?php echo $propertyId ?>">
				<option/>
						<?php foreach ($property['modalities'] as $modalityId => $modality) : ?>
                <option value="<?php echo $modalityId?>"><?php echo $modality[$context->getLocale()]?></option>
						<?php endforeach;?>
              </select>

					<?php elseif ($property['type'] == 'textarea') : ?>
              <textarea class="input_textarea" name="<?php echo $propertyId ?>" rows="8" cols="80" data-test="<?php echo $mandatory ?>"></textarea>

					<?php else : ?>
						<?php
						if ($field['type'] == 'text') $type = '';
						elseif ($field['type'] == 'number') $type = 'number';
						elseif ($field['type'] == 'email') $type = 'email';
						elseif ($field['type'] == 'phone') $type = 'number';
						?>
		      <input class="input_text" type="text" name="<?php echo $fieldId ?>" id="<?php echo $fieldId ?>" data-test="<?php echo $type ?> <?php echo $mandatory ?>">

					<?php endif?>
            </div>
            	<?php endif;?>

            <?php endforeach;?>

		<?php else : ?>

<!-- Simple field -->
            <div class="input_container">
              <label class="input_label" for="<?php echo $fieldId ?>"><?php if ($mandatory) echo '* '?><?php echo $field['labels'][$context->getLocale()]?></label>

			<?php if ($field['type'] == 'select') : ?>
              <select class="input_select" name="<?php echo $fieldId ?>" id="<?php echo $fieldId ?>">
				<option/>
				<?php foreach ($field['modalities'] as $modalityId => $modality) : ?>
                <option value="<?php echo $modalityId?>"><?php echo $modality[$context->getLocale()]?></option>
				<?php endforeach;?>
              </select>

			<?php elseif ($field['type'] == 'textarea') : ?>
              <textarea class="input_textarea" name="<?php echo $fieldId ?>" rows="8" cols="80" data-test="<?php echo $mandatory ?>"></textarea>

			<?php else : ?>
				<?php
				if ($field['type'] == 'text') $type = '';
				elseif ($field['type'] == 'number') $type = 'number';
				elseif ($field['type'] == 'email') $type = 'email';
				elseif ($field['type'] == 'phone') $type = 'number';
				?>
              <input class="input_text" type="text" name="<?php echo $fieldId ?>" id="<?php echo $fieldId ?>" data-test="<?php echo $type ?> <?php echo $mandatory ?>">

			<?php endif?>
            </div>

		<?php endif;?>

	<?php endforeach;?>

          </div>
        </div>
<?php endforeach;?>

        <div class="state_buttonContainer">
          <button class="state_button" type="submit">
            Étape suivante
            <span class="state_buttonArrow"></span>
          </button>
        </div>
      </div>
    </form>
  </section>
  <script src="<?php echo $this->basePath('dist/js/main.js') ?>" charset="utf-8"></script>
</body>
</html>
