<div class="panel panel-default">
	<div class="panel-heading">
		<?php echo $this->translate('Contact detail', 'ppit-contact', $context->getLocale()) ?>: <?php echo $contact->n_fn ?>
 		<div class="btn-group pull-right">
			<?php echo $this->partial('/partials/action-widget.phtml', array(
					'context' => $context,
					'target' => 'vcard-detail-panel-'.$contact->id,
					'glyphicon' => 'glyphicon-remove',
					'title' => $this->translate('Return to list', 'ppit-core', $context->getLocale()),
					'id' => 'remove-anchor-'.$contact->id,
			)) ?>
		</div>
	</div>
	<div class="panel-body">
		<table class="table-condensed">
			<tr>
				<td colspan="2">

<!-- Update -->
					<?php echo $this->partial('/partials/action-widget.phtml', array(
							'context' => $context,
							'target' => 'vcard-detail-panel-'.$contact->id,
							'glyphicon' => 'glyphicon-edit',
							'title' => $this->translate('Update', 'ppit-core', $context->getLocale()),
							'id' => 'update-anchor-'.$contact->id,
							'buttonColor' => ($contact->id == $context->getContactId()) ? 'btn-disabled' : 'btn-warning',
							'disabled' => $contact->id == $context->getContactId(),
							'route' => 'vcard/update',
							'params' => array('community_id' => $community_id, 'id' => $contact->id),
							'script' => 'vcard/update-'.$contact->id.'-script',
					)) ?>

<!-- Delete -->
					<?php echo $this->partial('/partials/action-widget.phtml', array(
							'context' => $context,
							'target' => 'vcard-update-panel-'.$contact->id,
							'glyphicon' => 'glyphicon-trash',
							'title' => $this->translate('Delete', 'ppit-core', $context->getLocale()),
							'id' => 'delete-anchor-'.$contact->id,
							'buttonColor' => ($contact->isDeletable()) ? 'btn-danger' : 'btn-disabled',
							'disabled' => !$contact->isDeletable(),
							'route' => 'vcard/delete',
							'params' => array('id' => $contact->id),
					)) ?>
				</td>
			</tr>
		</table>

		<div id="vcard-update-panel-<?php echo $contact->id ?>">

<!-- Photo -->
		    <div class="form-group" id="photo_group">
				<label class="col-sm-5 control-label">&nbsp;</label>
				<div class="col-sm-7">
					<a class="info" id="vcard_photo_anchor" href="#">
						<img height="150" src="<?php echo $this->url('vcard/photo', array('id' => $contact->id)) ?>"/>
					</a>
				</div>
			</div>

			<div>&nbsp;</div>

			<!-- Load the contact module -->
			<?php echo $this->partial('/partials/contact-update.phtml', array(
					'community_id' => $community_id,
					'communities' => array(),
					'message' => '',
					'contact' => $contact,
					'vcards' => array(),
					'config' => $config,
					'context' => $context,
					'isDisabled' => true
			)); ?>
		</div>

	</div>
</div>

<script id="vcard/detail-<?php echo $contact->id ?>-script">

eval(document.getElementById('remove-anchor-<?php echo $contact->id ?>-script').innerHTML);
eval(document.getElementById('update-anchor-<?php echo $contact->id ?>-script').innerHTML);

<?php if ($contact->isDeletable()) : ?>
	eval(document.getElementById('delete-anchor-<?php echo $contact->id ?>-script').innerHTML);
<?php endif;?>

</script>
