<?php
    echo $this->partial('/partials/menu');
?>
<?php $this->headTitle($title); ?>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
		<div class="panel panel-default">
            <div class="panel-heading">
				<strong><?php echo $this->translate($title);?></strong>
            </div>
           	<div class="panel-body">
<table class="table table-condensed">
<!--	<tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
		<td colspan="5">
			<a href="<?php echo $this->url('link/index', array('id' => 0));?>"><?php echo $this->translate('CSV imports') ?></a>
		</td>
	</tr> -->
	<tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td align="center"><strong><a href="<?php echo $this->url('vcard/index') ?>
											?major=n_fn
											<?php if ($major == 'n_fn' && $dir =='ASC') echo '&dir=DESC'; else echo '&dir=ASC' ?>">
			<?php echo $this->translate('Name');?></strong></td>
		<td align="center"><strong><?php echo $this->translate('Email');?></strong></td>
		<td align="center"><strong><?php echo $this->translate('Work phone');?></strong></td>
	</tr>
	<tr>
		<td colspan="5"><a href="<?php echo $this->url('vcard/add');?>"><img height="12" src="<?php echo $this->basePath('images/plus.png'); ?>" title="<?php echo $this->translate('Add') ?>" alt="<?php echo $this->translate('Add') ?>" /></a></td>
	</tr>
<?php foreach ($vcards as $vcard) : ?>
	<tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
		<td><a href="<?php echo $this->url('vcard/update', array('id' => $vcard->id));?>"><img height="12" src="<?php echo $this->basePath('images/edit_2.png'); ?>" title="<?php echo $this->translate('Update') ?>" alt="<?php echo $this->translate('Update') ?>" /></a></td>
		<td><a href="<?php echo $this->url('vcard/delete', array('id' => $vcard->id));?>"><img height="12" src="<?php echo $this->basePath('images/square_cross.png'); ?>" title="<?php echo $this->translate('Delete') ?>" alt="<?php echo $this->translate('Delete') ?>" /></a></td>
		<td align="center"><?php echo $vcard->n_fn ?></td>
		<td align="center"><a href="mailto:<?php echo isset($emails[$vcard->id]) ? $emails[$vcard->id] : null ?>"><?php echo isset($emails[$vcard->id]) ? $emails[$vcard->id] : null ?></a></td>
		<td align="center"><a href="tel:<?php echo isset($tels[$vcard->id]) ? $tels[$vcard->id] : null ?>"><?php echo isset($tels[$vcard->id]) ? $tels[$vcard->id] : null ?></a></td>
	</tr>
<?php endforeach; ?>
</table>
<?php //echo $this->paginationControl($this->vcards, 'Sliding', 'partials/pagination.phtml', (array('route' => 'vcard/index', 'major' => $major, 'dir' => $dir))); ?>
			</div>
		</div>
	</div>
</div>
