<div class="panel panel-default">
	<div class="panel-heading">
		<strong>
			<?php echo $this->translate('Contacts', 'ppit-contact', $context->getLocale());?>
<!--			(<span id="mode-text"><?php echo $this->translate('Todo list', 'ppit-core', $context->getLocale()) ?></span>) -->
		</strong>
	</div>
	<div class="panel-body">

<!-- Filters -->
	    <div>
	    		<span class="glyphicon glyphicon-search"></span>
	    		&nbsp;&nbsp;
	    		<input type="text" size="5" id="search_n_fn" placeholder="<?php echo $this->translate('Name', 'ppit-contact', $context->getLocale()) ?>" />
	    		&nbsp;&nbsp;
	    		<input type="text" size="5" id="search_email" placeholder="<?php echo $this->translate('Email', 'ppit-contact', $context->getLocale()) ?>" />
	    		&nbsp;&nbsp;
	    		<input type="text" size="5" id="search_tel_cell" placeholder="<?php echo $this->translate('Cellular', 'ppit-contact', $context->getLocale()) ?>" />
<?php if (!$properties || array_key_exists('tel_work', $properties)) : ?>
	    		&nbsp;&nbsp;
	    		<input type="text" size="5" id="search_tel_work" placeholder="<?php echo $this->translate('Work phone', 'ppit-contact', $context->getLocale()) ?>" />
<?php endif ?>
<?php if (!$properties || array_key_exists('adr_city', $properties)) : ?>
	    		&nbsp;&nbsp;
	    		<input type="text" size="5" id="search_adr_city" placeholder="<?php echo $this->translate('City', 'ppit-contact', $context->getLocale()) ?>" />
<?php endif ?>
<?php if (!$properties || array_key_exists('adr_state', $properties)) : ?>
				&nbsp;&nbsp;
	    		<input type="text" size="5" id="search_adr_state" placeholder="<?php echo $this->translate('State', 'ppit-contact', $context->getLocale()) ?>" />
<?php endif ?>
<?php if (!$properties || array_key_exists('adr_country', $properties)) : ?>
	    		&nbsp;&nbsp;
	    		<input type="text" size="5" id="search_adr_country" placeholder="<?php echo $this->translate('Country', 'ppit-contact', $context->getLocale()) ?>" />
<?php endif ?>
<?php if (!$properties || array_key_exists('sex', $properties)) : ?>
	    		&nbsp;&nbsp;
	    		<select id="search_sex" placeholder="<?php echo $this->translate('Sex', 'ppit-contact', $context->getLocale()) ?>">
					<option value=""><?php echo $this->translate('Sex', 'ppit-contact', $context->getLocale()) ?></option>
		    		<option value="F"><?php echo $this->translate('F', 'ppit-contact', $context->getLocale()) ?></option>
					<option value="M"><?php echo $this->translate('M', 'ppit-contact', $context->getLocale()) ?></option>
		    		<option value="?"><?php echo $this->translate('?', 'ppit-contact', $context->getLocale()) ?></option>
				</select>
<?php endif ?>
<?php if (!$properties || array_key_exists('birth_date', $properties)) : ?>
	    		&nbsp;&nbsp;
	    		<?php echo $this->translate('Birth', 'ppit-contact', $context->getLocale()) ?>:
	    		&nbsp;&nbsp;
	    		<input type="text" size="3" id="search_min_birth_date" placeholder="<?php echo $this->translate('Min', 'ppit-core', $context->getLocale()) ?>" />
	    		&nbsp;&nbsp;
	    		<input type="text" size="3" id="search_max_birth_date" placeholder="<?php echo $this->translate('Max', 'ppit-core', $context->getLocale()) ?>" />
<?php endif ?>
<?php if (!$properties || array_key_exists('place_of_birth', $properties)) : ?>
	    		&nbsp;&nbsp;
	    		<input type="text" size="5" id="search_place_of_birth" placeholder="<?php echo $this->translate('Place', 'ppit-contact', $context->getLocale()) ?>" />
<?php endif ?>
<?php if (!$properties || array_key_exists('nationality', $properties)) : ?>
	    		&nbsp;&nbsp;
	    		<input type="text" size="5" id="search_nationality" placeholder="<?php echo $this->translate('Nationality', 'ppit-contact', $context->getLocale()) ?>" />
<?php endif ?>
	    		&nbsp;&nbsp;
	    		<button type="button" class="btn btn-default btn-xs" title="<?php echo $this->translate('Erase', 'ppit-core', $context->getLocale()) ?>" id="erase-button">
					<span class="glyphicon glyphicon-remove"></span>
				</button>
	    </div>

	    <div>&nbsp;</div>

<!-- Actions -->
	    <div>
	    		<button type="button" class="btn btn-default" title="<?php echo $this->translate('Export', 'ppit-core', $context->getLocale()) ?>" id="export-button">
					<span class="glyphicon glyphicon-cloud-download"></span>
					<span><?php echo $this->translate('Export', 'ppit-core', $context->getLocale())?></span>
				</button>
	    </div>

	    <div>&nbsp;</div>

<!-- Add or update section -->
		<div id="vcard-list-panel"></div>
	</div>
</div>

<script id="vcard/search-script">

$("#search_min_birth_date").datepicker();
$("#search_max_birth_date").datepicker();

function getParams() {
	// Create a new FormData object.
	var params = '?', todo = true;

	var n_fn = document.getElementById('search_n_fn').value;
	if (n_fn.length >= 2) { params += 'n_fn=' + n_fn + '&'; todo = false; }

	var email = document.getElementById('search_email').value;
	if (email.length >= 2) { params += 'email=' + email + '&'; todo = false; }

	var tel_cell = document.getElementById('search_tel_cell').value;
	if (tel_cell.length >= 2) { params += 'tel_cell=' + tel_cell + '&'; todo = false; }

<?php if (!$properties || array_key_exists('tel_work', $properties)) : ?>
	var tel_work = document.getElementById('search_tel_work').value;
	if (tel_work.length >= 2) { params += 'tel_work=' + tel_work + '&'; todo = false; }
<?php endif ?>
	
<?php if (!$properties || array_key_exists('adr_city', $properties)) : ?>
	var adr_city = document.getElementById('search_adr_city').value;
	if (adr_city.length >= 2) { params += 'adr_city=' + adr_city + '&'; todo = false; }
<?php endif ?>

<?php if (!$properties || array_key_exists('adr_state', $properties)) : ?>
	var adr_state = document.getElementById('search_adr_state').value;
	if (adr_state.length >= 2) { params += 'adr_state=' + adr_state + '&'; todo = false; }
<?php endif ?>

<?php if (!$properties || array_key_exists('adr_country', $properties)) : ?>
	var adr_country = document.getElementById('search_adr_country').value;
	if (adr_country.length >= 2) { params += 'adr_country=' + adr_country + '&'; todo = false; }
<?php endif ?>

<?php if (!$properties || array_key_exists('sex', $properties)) : ?>
	var sex = document.getElementById('search_sex').value;
	if (sex != '') { params += 'sex=' + sex + '&'; todo = false; }
<?php endif ?>

<?php if (!$properties || array_key_exists('birth_date', $properties)) : ?>
	var min_birth_date = document.getElementById('search_min_birth_date').value;
	if (min_birth_date) min_birth_date = encodeDate(min_birth_date);
	if (min_birth_date.length >= 2) { params += 'min_birth_date=' + min_birth_date + '&'; todo = false; }

	var max_birth_date = document.getElementById('search_max_birth_date').value;
	if (max_birth_date) max_birth_date = encodeDate(max_birth_date);
	if (max_birth_date.length >= 2) { params += 'max_birth_date=' + max_birth_date + '&'; todo = false; }
<?php endif ?>

<?php if (!$properties || array_key_exists('place_of_birth', $properties)) : ?>
	var place_of_birth = document.getElementById('search_place_of_birth').value;
	if (place_of_birth.length >= 2) { params += 'place_of_birth=' + place_of_birth + '&'; todo = false; }
<?php endif ?>

<?php if (!$properties || array_key_exists('nationality', $properties)) : ?>
	var nationality = document.getElementById('search_nationality').value;
	if (nationality.length >= 2) { params += 'nationality=' + nationality + '&'; todo = false; }
<?php endif ?>

	return params;
}

// Show the list
function getVcardList() {	

	params = getParams();
	
//	$('#mode-text').text((todo) ? '<?php echo $this->translate('Todo list', 'ppit-core', $context->getLocale())?>' : '<?php echo $this->translate('Search', 'ppit-core', $context->getLocale())?>');
	
	var xhttp = new XMLHttpRequest();
	xhttp.onreadystatechange = function() {
		if (xhttp.readyState == 4<?php if (!$config['ppitCoreSettings']['isTraceActive']) echo ' && xhttp.status == 200' ?>) {
			document.getElementById('vcard-list-panel').innerHTML = xhttp.responseText;
<?php if ($config['ppitCoreSettings']['isTraceActive']) : ?>
			console.log('getVcardList, route = ' + '<?php echo $this->url('vcard/list', array('community_id' => $community_id)) ?>' + params);
			console.log(xhttp.responseText);
<?php endif;?>
			eval(document.getElementById('vcard/list-script').innerHTML);
		}
	}
	xhttp.open('GET', '<?php echo $this->url('vcard/list', array('community_id' => $community_id)) ?>' + params, true);
	xhttp.send();
}

// Export the list
function exportVcardList() {

	params = getParams();
	document.location.href = '<?php echo $this->url('vcard/export', array('community_id' => $community_id)) ?>' + params;
}

$('#export-button').click(exportVcardList);

// Events on search inputs
$('#search_n_fn').keyup(getVcardList);
$('#search_search_email').keyup(getVcardList);
$('#search_tel_cell').keyup(getVcardList);

<?php if (!$properties || array_key_exists('tel_work', $properties)) : ?>
	$('#search_tel_work').keyup(getVcardList);
<?php endif ?>

<?php if (!$properties || array_key_exists('adr_city', $properties)) : ?>
	$('#search_adr_city').keyup(getVcardList);
<?php endif ?>

<?php if (!$properties || array_key_exists('adr_state', $properties)) : ?>
	$('#search_adr_state').keyup(getVcardList);
<?php endif ?>

<?php if (!$properties || array_key_exists('adr_country', $properties)) : ?>
	$('#search_adr_country').keyup(getVcardList);
<?php endif ?>

<?php if (!$properties || array_key_exists('sex', $properties)) : ?>
	$('#search_sex').change(getVcardList);
<?php endif ?>

<?php if (!$properties || array_key_exists('birth_date', $properties)) : ?>
	$('#search_min_birth_date').change(getVcardList);
	$('#search_max_birth_date').change(getVcardList);
<?php endif ?>

<?php if (!$properties || array_key_exists('place_of_birth', $properties)) : ?>
	$('#search_place_of_birth').keyup(getVcardList);
<?php endif ?>

<?php if (!$properties || array_key_exists('nationality', $properties)) : ?>
	$('#search_nationality').keyup(getVcardList);
<?php endif ?>
	
$('#erase-button').click(function () {
	$('#search_n_fn').val('');
	$('#search_email').val('');
	$('#search_tel_cell').val('');

<?php if (!$properties || array_key_exists('tel_work', $properties)) : ?>
	$('#search_tel_work').val('');
<?php endif ?>

<?php if (!$properties || array_key_exists('adr_city', $properties)) : ?>
	$('#search_adr_city').val('');
<?php endif ?>

<?php if (!$properties || array_key_exists('adr_state', $properties)) : ?>
	$('#search_adr_state').val('');
<?php endif ?>

<?php if (!$properties || array_key_exists('adr_country', $properties)) : ?>
	$('#search_adr_country').val('');
<?php endif ?>

<?php if (!$properties || array_key_exists('sex', $properties)) : ?>
	$('#search_sex').val('');
<?php endif ?>

<?php if (!$properties || array_key_exists('birth_date', $properties)) : ?>
	$('#search_min_birth_date').val('');
	$('#search_max_birth_date').val('');
<?php endif ?>

<?php if (!$properties || array_key_exists('place_of_birth', $properties)) : ?>
	$('#search_place_of_birth').val('');
<?php endif ?>

<?php if (!$properties || array_key_exists('nationality', $properties)) : ?>
	$('#search_nationality').val('');
<?php endif ?>

	getVcardList();
});

getVcardList();
					
</script>
