<?php
	$title = $this->translate('Contacts', 'ppit-contact', $current_user->locale);
	echo $this->partial('/partials/menu');
?>
<?php
$this->headTitle($title);
?>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
		<div class="panel panel-default">
            <div class="panel-heading">
				<strong><?php echo $this->translate($this->translate('Update a contact', 'ppit-contact', $current_user->locale));?></strong>
            </div>
           	<div class="panel-body">
				
<!-- Form opening tag -->
				<form action="<?php echo $this->url('vcard/update', array('id' => $id)) ?>" method="post" name="vcard" class="form-horizontal" enctype="form-data" id="vcard" onSubmit="return checkForm()">

<!--  Duplicate error -->
				    <div class="form-group">
<?php if ($error == 'Duplicate') : ?>
						<div class="col-sm-12"><p class="help-block"><?php echo $this->translate('A contact with the same email or cellular phone number already exists', 'ppit-contact', $current_user->locale) ?></p></div>
<?php endif;?>
					</div>
				
<!--  CSRF -->
<?php $element = $csrfForm->get('csrf') ?>
				    <div class="form-group">
						<?php echo $this->formElement($element) ?>
<?php if ($this->formElementErrors($element)) : ?>
						<div class="col-sm-12"><p class="help-block"><?php echo $this->translate('The form has expired, please input again', 'ppit-core', $current_user->locale) ?></p></div>
<?php endif;?>
					</div>

<!-- Title -->
				    <div class="form-group" id="n_title_group">
						<label class="col-sm-4 control-label"><?php echo $this->translate('Title', 'ppit-contact', $current_user->locale) ?></label>
						<div class="col-sm-8">
							<input name="n_title" id="n_title" class="form-control" value="<?php echo $vcard->n_title ?>">
						</div>
						<div class="col-sm-12"><p class="help-block" id="n_title_error"></p></div>
					</div>
					
<!-- First name -->
				    <div class="form-group" id="n_first_group">
						<label class="col-sm-4 control-label">* <?php echo $this->translate('First name', 'ppit-contact', $current_user->locale) ?></label>
						<div class="col-sm-8">
							<input name="n_first" id="n_first" class="form-control" value="<?php echo $vcard->n_first ?>">
						</div>
						<div class="col-sm-12"><p class="help-block" id="n_first_error"></p></div>
					</div>

<!-- Last name -->
				    <div class="form-group" id="n_last_group">
						<label class="col-sm-4 control-label">* <?php echo $this->translate('Last name', 'ppit-contact', $current_user->locale) ?></label>
						<div class="col-sm-8">
							<input name="n_last" id="n_last" class="form-control" value="<?php echo $vcard->n_last ?>">
						</div>
						<div class="col-sm-12"><p class="help-block" id="n_last_error"></p></div>
					</div>
					
<!-- Organisation -->
				    <div class="form-group" id="org_group">
						<label class="col-sm-4 control-label"><?php echo $this->translate('Organisation', 'ppit-contact', $current_user->locale) ?></label>
						<div class="col-sm-8">
							<input name="org" id="org" class="form-control" value="<?php echo $vcard->org ?>">
						</div>
						<div class="col-sm-12"><p class="help-block" id="org_error"></p></div>
					</div>
					
<!-- Email -->
				    <div class="form-group" id="email_group">
						<label class="col-sm-4 control-label">* <?php echo $this->translate('Email', 'ppit-contact', $current_user->locale) ?></label>
						<div class="col-sm-8">
							<input name="email" id="email" class="form-control" value="<?php echo $vcard->email ?>">
						</div>
						<div class="col-sm-12"><p class="help-block" id="email_error"></p></div>
					</div>

<!-- Work phone -->
				    <div class="form-group" id="tel_work_group">
						<label class="col-sm-4 control-label"> <?php echo $this->translate('Work phone', 'ppit-contact', $current_user->locale) ?></label>
						<div class="col-sm-8">
							<input name="tel_work" id="tel_work" class="form-control" value="<?php echo $vcard->tel_work ?>">
						</div>
						<div class="col-sm-12"><p class="help-block" id="tel_work_error"></p></div>
					</div>

<!-- Cellular phone -->
				    <div class="form-group" id="tel_cell_group">
						<label class="col-sm-4 control-label"> <?php echo $this->translate('Cellular phone', 'ppit-contact', $current_user->locale) ?></label>
						<div class="col-sm-8">
							<input name="tel_cell" id="tel_cell" class="form-control" value="<?php echo $vcard->tel_cell ?>">
						</div>
						<div class="col-sm-12"><p class="help-block" id="tel_cell_error"></p></div>
					</div>

<!-- Address - street -->
				    <div class="form-group" id="ADR_street_group">
						<label class="col-sm-4 control-label"> <?php echo $this->translate('Address - street', 'ppit-contact', $current_user->locale) ?></label>
						<div class="col-sm-8">
							<input name="ADR_street" id="ADR_street" class="form-control" value="<?php echo $vcard->ADR_street ?>">
						</div>
						<div class="col-sm-12"><p class="help-block" id="ADR_street_error"></p></div>
					</div>

<!-- Address - extended -->
				    <div class="form-group" id="ADR_extended_group">
						<label class="col-sm-4 control-label"> <?php echo $this->translate('Address - extended', 'ppit-contact', $current_user->locale) ?></label>
						<div class="col-sm-8">
							<input name="ADR_extended" id="ADR_extended" class="form-control" value="<?php echo $vcard->ADR_extended ?>">
						</div>
						<div class="col-sm-12"><p class="help-block" id="ADR_extended_error"></p></div>
					</div>

<!-- Address - Post office box -->
				    <div class="form-group" id="ADR_post_office_box_group">
						<label class="col-sm-4 control-label"> <?php echo $this->translate('Address - post office box', 'ppit-contact', $current_user->locale) ?></label>
						<div class="col-sm-8">
							<input name="ADR_post_office_box" id="ADR_post_office_box" class="form-control" value="<?php echo $vcard->ADR_post_office_box ?>">
						</div>
						<div class="col-sm-12"><p class="help-block" id="ADR_post_office_box_error"></p></div>
					</div>

<!-- Address - zip -->
				    <div class="form-group" id="ADR_zip_group">
						<label class="col-sm-4 control-label"> <?php echo $this->translate('Address - zip', 'ppit-contact', $current_user->locale) ?></label>
						<div class="col-sm-8">
							<input name="ADR_zip" id="ADR_zip" class="form-control" value="<?php echo $vcard->ADR_zip ?>">
						</div>
						<div class="col-sm-12"><p class="help-block" id="ADR_zip_error"></p></div>
					</div>

<!-- Address - city -->
				    <div class="form-group" id="ADR_city_group">
						<label class="col-sm-4 control-label"> <?php echo $this->translate('Address - city', 'ppit-contact', $current_user->locale) ?></label>
						<div class="col-sm-8">
							<input name="ADR_city" id="ADR_city" class="form-control" value="<?php echo $vcard->ADR_city ?>">
						</div>
						<div class="col-sm-12"><p class="help-block" id="ADR_city_error"></p></div>
					</div>

<!-- Address - state -->
				    <div class="form-group" id="ADR_state_group">
						<label class="col-sm-4 control-label"> <?php echo $this->translate('Address - state', 'ppit-contact', $current_user->locale) ?></label>
						<div class="col-sm-8">
							<input name="ADR_state" id="ADR_state" class="form-control" value="<?php echo $vcard->ADR_state ?>">
						</div>
						<div class="col-sm-12"><p class="help-block" id="ADR_state_error"></p></div>
					</div>
					
<!-- Address - country -->
				    <div class="form-group" id="ADR_country">
						<label class="col-sm-4 control-label"> <?php echo $this->translate('Address - country', 'ppit-contact', $current_user->locale) ?></label>
						<div class="col-sm-8">
							<input name="ADR_country" id="ADR_country" class="form-control" value="<?php echo $vcard->ADR_country ?>">
						</div>
						<div class="col-sm-12"><p class="help-block" id="ADR_country_error"></p></div>
					</div>
					
<!-- Submit button -->
				    <div class="form-group">
						<div class="col-sm-4">&nbsp;</div>
						<div class="col-sm-8">
							<input name="submit" type="submit" id="submitbutton" class="btn btn-primary" value="<?php echo $this->translate('Submit', 'ppit-core', $current_user->locale) ?>">
							&nbsp;&nbsp;
							<a href="<?php echo $this->url('vcard') ?>"><?php echo $this->translate('Cancel', 'ppit-core', $current_user->locale) ?></a>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

<!-- Load the common form javascript functions -->
<?php echo $this->partial('/partials/common-form-js.phtml'); ?>

<script>

// The elements are checked last to first so the focus is positionned on the first element on error
function checkForm() 
{
	var validity = true;	
	
	// Address - country
	if (document.getElementById("ADR_country").value.length > 255) {
		renderElement("ADR_country", "<?php echo $this->translate('The input is too long', 'ppit-core', $current_user->locale) ?>");
		validity = false;
	}
    else {
		renderElement("ADR_country", null);
	}
	
	// Address - state
	if (document.getElementById("ADR_state").value.length > 255) {
		renderElement("ADR_state", "<?php echo $this->translate('The input is too long', 'ppit-core', $current_user->locale) ?>");
		validity = false;
	}
    else {
		renderElement("ADR_state", null);
	}
	
	// Address - city
	if (document.getElementById("ADR_city").value.length > 255) {
		renderElement("ADR_city", "<?php echo $this->translate('The input is too long', 'ppit-core', $current_user->locale) ?>");
		validity = false;
	}
    else {
		renderElement("ADR_city", null);
	}
	
	// Address - zip
	if (document.getElementById("ADR_zip").value.length > 255) {
		renderElement("ADR_zip", "<?php echo $this->translate('The input is too long', 'ppit-core', $current_user->locale) ?>");
		validity = false;
	}
    else {
		renderElement("ADR_zip", null);
	}
	
	// Address - post office box
	if (document.getElementById("ADR_post_office_box").value.length > 255) {
		renderElement("ADR_post_office_box", "<?php echo $this->translate('The input is too long', 'ppit-core', $current_user->locale) ?>");
		validity = false;
	}
    else {
		renderElement("ADR_post_office_box", null);
	}
	
	// Address - extended
	if (document.getElementById("ADR_extended").value.length > 255) {
		renderElement("ADR_extended", "<?php echo $this->translate('The input is too long', 'ppit-core', $current_user->locale) ?>");
		validity = false;
	}
    else {
		renderElement("ADR_extended", null);
	}
	
	// Address - street
	if (document.getElementById("ADR_street").value.length > 255) {
		renderElement("ADR_street", "<?php echo $this->translate('The input is too long', 'ppit-core', $current_user->locale) ?>");
		validity = false;
	}
    else {
		renderElement("ADR_street", null);
	}

	var error;
	
	// Cellular phone
	var tel_cell_validity = true;
	error = checkPhone(document.getElementById('tel_cell').value);
	if (error) {
		renderElement("tel_cell", error);
		validity = tel_cell_validity = false;
	}
	    else {
		renderElement("tel_cell", null);
	}
	
	// Work phone
	var tel_work_validity = true;
	error = checkPhone(document.getElementById('tel_work').value);
	if (error) {
		renderElement("tel_work", error);
		validity = tel_work_validity = false;
	}
	else {
		renderElement("tel_work", null);
	}

	// 1 mandatory phone
	if (tel_cell_validity && tel_work_validity) {
		if (document.getElementById("tel_work").value == "" && document.getElementById("tel_cell").value == "") {
			renderElement("tel_cell", "<?php echo $this->translate('Please input at least one phone', 'ppit-contact', $current_user->locale) ?>");
			renderElement("tel_work", "<?php echo $this->translate('Please input at least one phone', 'ppit-contact', $current_user->locale) ?>");
			validity = false;
		}
	    else {
			renderElement("tel_cell", null);
	    	renderElement("tel_work", null);
		}
	}
	
	// Email
	var email_validity = true;
	var email = document.getElementById('email').value;
	if (email == "") renderElement("email", null);
	else {
		error = checkEmail(email);
		if (error) {
			renderElement("email", error);
			validity = email_validity = false;
		}
	    else {
			renderElement("email", null);
		}
	}

	// At least email or cellular
	if (tel_cell_validity && email_validity) {
		if (document.getElementById("tel_cell").value == "" && document.getElementById("email").value == "") {
			renderElement("email", "<?php echo $this->translate('Please input at least the cellular or the email', 'ppit-contact', $current_user->locale) ?>");
			renderElement("tel_cell", "<?php echo $this->translate('Please input at least the cellular or the email', 'ppit-contact', $current_user->locale) ?>");
			validity = false;
		}
	    else {
			renderElement("email", null);
	    	renderElement("tel_cell", null);
		}
	}
	
	// Organisation
	if (document.getElementById("org").value.length > 255) {
		renderElement("org", "<?php echo $this->translate('The input is too long', 'ppit-core', $current_user->locale) ?>");
		validity = false;
	}
    else {
		renderElement("org", null);
	}
	
	// Last name
	if (document.getElementById("n_last").value == "") {
		renderElement("n_last", "<?php echo $this->translate('Please input the last name', 'ppit-contact', $current_user->locale) ?>");
		validity = false;
	}
    else if (document.getElementById("n_last").value.length > 255) {
		renderElement("n_last", "<?php echo $this->translate('The input is too long', 'ppit-core', $current_user->locale) ?>");
		validity = false;
	}
    else {
		renderElement("n_last", null);
	}
	
	// First name
	if (document.getElementById("n_first").value == "") {
		renderElement("n_first", "<?php echo $this->translate('Please input the first name', 'ppit-contact', $current_user->locale) ?>");
		validity = false;
	}
    else if (document.getElementById("n_first").value.length > 255) {
		renderElement("n_last", "<?php echo $this->translate('The input is too long', 'ppit-core', $current_user->locale) ?>");
		validity = false;
	}
    else {
		renderElement("n_first", null);
	}
	
	// Title
	if (document.getElementById("n_title").value.length > 255) {
		renderElement("n_title", "<?php echo $this->translate('The input is too long', 'ppit-core', $current_user->locale) ?>");
		validity = false;
	}
    else {
		renderElement("n_title", null);
	}
		
	return validity;
}

</script>
